### ISSUE TITLE
[PE-D] Find command by date does not work

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-W17-4/tp#257]
![Screenshot 2021-10-29 at 4.44.59 PM.png](https://raw.githubusercontent.com/jaredlhf/ped/main/files/2648fd20-a17e-4783-860b-30555d8ffe8b.png)

![Screenshot 2021-10-29 at 4.45.28 PM.png](https://raw.githubusercontent.com/jaredlhf/ped/main/files/a802bc95-86e8-4280-b4f8-2c671494be40.png)

* UG example `find` command does not work

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: jaredlhf/ped#5

**Comment by KelvinSoo** [comment]
Same issue as #249
