### ISSUE TITLE
[PE-D] Command Summary Table Markdown Formatting

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-W17-4/tp#267]
Formatting for second row is incorrect. e.g. is highlighted as a command and code tag is showing.

![image.png](https://raw.githubusercontent.com/rohit0718/ped/main/files/0a4df658-ffc8-4a82-a379-57e4d90cd5a8.png)

Italics tags are also showing.

![image.png](https://raw.githubusercontent.com/rohit0718/ped/main/files/cd017579-a6ed-4fc0-97d3-3ef56b92f109.png)

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: rohit0718/ped#15

**Comment by KelvinSoo** [comment]
Same issues as #247
