### ISSUE TITLE
[PE-D] Link in help box directs to AB3 UG

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-W17-4/tp#269]
![image.png](https://raw.githubusercontent.com/pualixue/ped/main/files/9abdeab0-4955-4290-860c-7de2bd5da1fa.png)

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: pualixue/ped#12

**Comment by KelvinSoo** [comment]
Same issues as #223
