### ISSUE TITLE
[PE-D] find command by tag does not work as expected

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-W17-4/tp#273]
![Screenshot 2021-10-29 at 5.10.32 PM.png](https://raw.githubusercontent.com/jaredlhf/ped/main/files/d5a086be-15cf-4fa7-b3c9-32518dc7b32c.png)
![Screenshot 2021-10-29 at 5.11.02 PM.png](https://raw.githubusercontent.com/jaredlhf/ped/main/files/7734f4d9-b16d-4408-ac5f-77530ac7db7a.png)

![Screenshot 2021-10-29 at 5.10.48 PM.png](https://raw.githubusercontent.com/jaredlhf/ped/main/files/f820c515-3d3f-4e14-bdbb-91c1ec61a17d.png)

* `find t/CS1234` should return 1 task but returns 0 tasks instead

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: jaredlhf/ped#7

**Comment by KelvinSoo** [comment]
Same issue as #252
