### ISSUE TITLE
[PE-D] find is unable to list all tasks

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-W17-4/tp#274]
* Unable to revert back to a page where my entire Task List is shown, have to restart the app every time I want to view all my existing tasks
* makes it hard to view all my `tasks` if i wish to do so

* perhaps a `find` command without any parameters or a `find all` command 

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: jaredlhf/ped#8

**Comment by KelvinSoo** [comment]
The list command shows all tasks.

**Comment by KelvinSoo** [comment]
Missing list command in UG
