### ISSUE TITLE
Edit Command: edit priority does not work

### ISSUE THREAD

**Issue by KelvinSoo** [AY2122S1-CS2103T-W17-4/tp#290]
#### Issue description

edit does not allow the use of p/priority field

#### Steps to reproduce the issue

1.  attempt to change the priority of any task
2.  get Invalid command format! 

#### What's the expected result?

- priority of the task to be edited

#### What's the actual result?

- error

#### Additional details / screenshot
![image](https://user-images.githubusercontent.com/77185437/140305325-21892c76-6ecd-4026-b9d8-55c95df40017.png)

**Comment by naranghardik16** [comment]
Have fixed the edit command to allow editing the priority of a task.
