### ISSUE TITLE
NullPointerException Faced when running the Main Class

### ISSUE THREAD

**Issue by Dr-Octavius** [AY2122S1-CS2103T-W17-4/tp#64]
![image](https://user-images.githubusercontent.com/65051094/136402175-b0c1c72d-8fc1-4a60-933f-de20491083ee.png)
Attached above is the problem as seen on the GUI

![image](https://user-images.githubusercontent.com/65051094/136402320-e278266a-6827-4ad5-bc93-c5576de99250.png)
UIManager Class seems to be having an issue in that the start function is facing a null input as reflected

**Comment by KelvinSoo** [comment]
![image](https://user-images.githubusercontent.com/77185437/136509487-150e9ada-f726-4ab4-85a9-2fabdf7a6df1.png)
TaskListPanel.java is looking for TaskListPanel.fxml.
![image](https://user-images.githubusercontent.com/77185437/136509526-7ebc4ba4-5001-4802-845b-4707a261b286.png)
But the file name is PersonListPanel.fxml.
